### ISSUE TITLE
[FEATURE] 1.18.2 Version

### ISSUE THREAD

**Issue by ENC4YP7ED** [Negodya1/Create-Vintage-Improvements#11]
I would like to have the mod on 1.18.2 even if it is just one time

**Comment by Negodya1** [comment]
Ok, I will port the mod to the 1.18.2 after the new version comes out

**Comment by ENC4YP7ED** [comment]
> Ok, I will port the mod to the 1.18.2 after the new version comes out

Do you have an eta ?

**Comment by Negodya1** [comment]
It's done

**Comment by ENC4YP7ED** [comment]
> It's done

oh nice so where can I download the 1.18.2 version ?

**Comment by Negodya1** [comment]
[CurseForge](https://www.curseforge.com/minecraft/mc-mods/create-vintage-improvements) or [Modrinth](https://modrinth.com/mod/create-vintage-improvements)
