### ISSUE TITLE
[1.20.1] Server Crash on start

### ISSUE THREAD

**Issue by FrozenGalaxy** [Negodya1/Create-Vintage-Improvements#12]
crash dump: https://gist.github.com/FrozenGalaxy/263a92775da14565aebc6640f1b2dbf1

**Comment by Negodya1** [comment]
Does it happen every start? Because I'v tested neoforge (47.1.101) client & server runs and it happens only once among 50 starts on client

**Comment by Negodya1** [comment]
Some changes in last versions probably fix this issue

**Comment by shadow7483147** [comment]
> Some changes in last versions probably fix this issue

Confirming, updating from 0.1.3.1 to 0.1.3.4 fixed the startup crash. (Via Gregtech New Beginnings modpack)

**Comment by Negodya1** [comment]
Probably fixed
