### ISSUE TITLE
1.20.1 Crash on World Creation 

### ISSUE THREAD

**Issue by CaptainPepperjack** [Negodya1/Create-Vintage-Improvements#14]
[crash-2024-03-14_10.07.06-server.txt](https://github.com/Negodya1/Create-Vintage-Improvements/files/14603500/crash-2024-03-14_10.07.06-server.txt)

**Comment by Negodya1** [comment]
Some recipe couse a crash. I found a reason. Try this version
[vintageimprovements-1.20.1-0.1.3.0a.zip](https://github.com/Negodya1/Create-Vintage-Improvements/files/14604932/vintageimprovements-1.20.1-0.1.3.0a.zip)
