### ISSUE TITLE
The shaft of the helve hammmer is not rendering

### ISSUE THREAD

**Issue by DariusZeBaguette** [Negodya1/Create-Vintage-Improvements#15]
I am in forge 1.19.2 1.3.0, and i don't know if it comes from only the mod or because i have embeddium, but the shaft on the helve hammer is not rendering in game, even in ponders. but in hand it works fine
![image](https://github.com/Negodya1/Create-Vintage-Improvements/assets/128926506/520d5351-1043-46ec-aec9-bd4bc9881470)

**Comment by Negodya1** [comment]
Fixed
