### ISSUE TITLE
invalid placement of the outline of the helve hammer is not dispayed correctly

### ISSUE THREAD

**Issue by DariusZeBaguette** [Negodya1/Create-Vintage-Improvements#16]
![image](https://github.com/Negodya1/Create-Vintage-Improvements/assets/128926506/949a5485-6561-4fc2-b54e-dd94ed7163bd)
if you don't have enough place the helve hammer, it will show an outline showing the blocks you need to break, but the outline is centered on the block you click, and the when placing the hammer, its placed on the edge, so it display this stupid thing where it tells there is blocks in the way but there is nothing but only air.
1.19.2 forge 1.3.0
the easiest way of patching it would be to make that when placing the helve hammer, it actually place it centered on the block you right clicked

**Comment by Negodya1** [comment]
Helve Hammer placing will be improved in 0.1.3.2 version

**Comment by Negodya1** [comment]
Fixed
