### ISSUE TITLE
Helve hammer not dropping in survival and particles issue

### ISSUE THREAD

**Issue by DariusZeBaguette** [Negodya1/Create-Vintage-Improvements#17]
1.19.2 1.3.0 forge
when breaking a helve hammer, it doesnt drop itself in survival
and when breaking it, the particles are only displayed on the hammer metal thing part of the block, and not on the other parts like the "log" and the casing part

**Comment by Negodya1** [comment]
Drops fixed. Particles works just like a large water wheel
