### ISSUE TITLE
Question: Can I add my own recipe's to the machines added by this mod?

### ISSUE THREAD

**Issue by evertn** [Negodya1/Create-Vintage-Improvements#2]
As the title suggests, can I add my own recipe's to the machines added by this mod? Or is there any KubeJS support planned?

I really like the machines in this mod and I think they can go really well with some other mods too.

**Comment by Negodya1** [comment]
Yes, you can add/change/remove recipes by datapacks system. Also all machines supports sequenced assembly recipes, if you need.

KubeJS? I will think about it, maybe in some future update.

**Comment by Negodya1** [comment]
Datapack example

[Vintage Improvements datapack example.zip](https://github.com/Negodya1/Create-Vintage-Improvements/files/14233651/Vintage.Improvements.datapack.example.zip)

**Comment by evertn** [comment]
Ah, thanks.

Is it an idea to place these in your mod description, or here on GitHub? Im assuming new machines will still be added? I would like to have examples for those too.

Thanks in advance.

Keep up the good work!

**Comment by Negodya1** [comment]
New machines are not planned for the near future. Right now I'm focused on adding some utilities to the mod.

I will put some recipes information to the GitHub wiki
