### ISSUE TITLE
Fails to join server after install update 

### ISSUE THREAD

**Issue by VillainVibe** [Negodya1/Create-Vintage-Improvements#22]
After installing the update: version 1.20.1-0.1.4.0 on both client and server I'm no longer able to log into my server.

Log of the console from the client

[log.txt](https://github.com/Negodya1/Create-Vintage-Improvements/files/15102287/log.txt)

If you need more info just ask.

**Comment by Azzmurr** [comment]
We also have the same issue. It says this.itemAsHead is null

**Comment by BryhanFine** [comment]
Same issue with error: lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.Item.toString()" because "this.itemAsHead" is null

**Comment by Negodya1** [comment]
I found a reason

**Comment by Negodya1** [comment]
Fixed

**Comment by Negodya1** [comment]
Hotfix released, already on Modrinth (CurseForge version appear after moderation)

**Comment by sayore** [comment]
Tysm Github search to find THIS specific issue. 🙏

**Comment by VillainVibe** [comment]
> Hotfix released, already on Modrinth (CurseForge version appear after moderation)

Thank you for fixing this so quick.
Cheers!
