### ISSUE TITLE
[Suggestion] Add Visual Indicator Redstone Module is Installed

### ISSUE THREAD

**Issue by VoidLeech** [Negodya1/Create-Vintage-Improvements#23]
Currently, the only way to determine whether a redstone module is installed on a centrifuge is to break it, try to install another module, or test whether a recipe gets recognized. None of these are desireable methods when you want to quickly check which centrifuges you still need to upgrade or which centrifuge is your control centrifuge (with parallelized inputs).

**Comment by Negodya1** [comment]
You can check module with glasses, but I will add some visual indicator in 0.1.4.2

**Comment by Negodya1** [comment]
Done
