### ISSUE TITLE
Curving: Impossible to create multiple recipes with the same input, but with different heads.

### ISSUE THREAD

**Issue by vililichi** [Negodya1/Create-Vintage-Improvements#26]
When there is more than one recipe with the same input, only the first recipe works, even if the head used is different.
Other recipes are displayed in jei but do not work.

I can see the craft in JEI:
![exemple1](https://github.com/Negodya1/Create-Vintage-Improvements/assets/55566485/0822f81e-b1ba-4f3d-8a84-6d05adeb7a30)
![exemple2](https://github.com/Negodya1/Create-Vintage-Improvements/assets/55566485/1e43f82f-6921-4456-aa07-ab00d19ebdbf)

But when I try it, nothing happen. Only the first craft displayed in jei works:
![image](https://github.com/Negodya1/Create-Vintage-Improvements/assets/55566485/eca54dd1-0069-4e2f-8665-10fcf67c251f)

Mods:
Create
Create-Vintage-Improvements
Kubejs

**Comment by Negodya1** [comment]
I will fix this in the next version

**Comment by Negodya1** [comment]
Fixed

**Comment by vililichi** [comment]
The problem is still present with custom heads
