### ISSUE TITLE
Curving: custom head texture disparition

### ISSUE THREAD

**Issue by vililichi** [Negodya1/Create-Vintage-Improvements#27]
The texture of custom heads added with Kubejs disappears after a craft or after the curving press is updated.

Model before I put the custom head:
![image](https://github.com/Negodya1/Create-Vintage-Improvements/assets/55566485/345e1389-781b-467b-b4e8-911ee36d43f0)

Model after I put the custom head:
![image](https://github.com/Negodya1/Create-Vintage-Improvements/assets/55566485/ac53dc7b-986d-4aa7-ace8-2a8ecb7aba34)

Model after a craft or an update:
![image](https://github.com/Negodya1/Create-Vintage-Improvements/assets/55566485/a1861c7f-cc0f-4a0a-89c7-712b7bd1d30a)

Kubejs scripts:
[kubejs.zip](https://github.com/Negodya1/Create-Vintage-Improvements/files/15380697/kubejs.zip)

Mods:
Create
Create-Vintage-Improvements
Kubejs

**Comment by Negodya1** [comment]
Fixed
