### ISSUE TITLE
Auto added curving recepies inconsist with manualy added

### ISSUE THREAD

**Issue by AlexIlyn** [Negodya1/Create-Vintage-Improvements#28]
If enable in config "allowAutoCurvingRecipes" curving press can have auto added recepie with multiple input items  example "3 Iron Ingot to Bucket"
![image](https://github.com/Negodya1/Create-Vintage-Improvements/assets/22565509/3595ccf6-6b45-45c2-acf5-ca28f9b12ff4)

If added manually this is not working:
`{
	"type": "vintageimprovements:curving",
	"mode": 1,
	"ingredients": [
		{
		  "item": "minecraft:iron_ingot"
		},
		{
		  "item": "minecraft:iron_ingot"
		},
		{
		  "item": "minecraft:iron_ingot"
		}
	],
	"results": [
		{
		  "item": "minecraft:bucket"
		}
	]
}`
![image](https://github.com/Negodya1/Create-Vintage-Improvements/assets/22565509/772db5ef-807d-44d2-8858-b65628c98912)

**Comment by Negodya1** [comment]
Fixed
