### ISSUE TITLE
[1.20.1-v0.1.4.2] Curving: Impossible to create multiple recipes with the same input, but with different custom heads.

### ISSUE THREAD

**Issue by vililichi** [Negodya1/Create-Vintage-Improvements#29]
This bug is similar to https://github.com/Negodya1/Create-Vintage-Improvements/issues/26 but only for custom head.
When there is more than one recipe with the same input, only the first recipe works with custom head, even if the custom heads used are different.
Other recipes are displayed in jei but do not work.

I can see the craft in JEI:
![exemple2](https://github.com/Negodya1/Create-Vintage-Improvements/assets/55566485/1e43f82f-6921-4456-aa07-ab00d19ebdbf)

But when I try it, nothing happen. Only the first craft displayed in jei works:
![image](https://github.com/Negodya1/Create-Vintage-Improvements/assets/55566485/eca54dd1-0069-4e2f-8665-10fcf67c251f)

Mods:
Create
Create-Vintage-Improvements
Kubejs

**Comment by Negodya1** [comment]
Fixed
