### ISSUE TITLE
[1.20.1] Curving press JEI/EMI bug

### ISSUE THREAD

**Issue by ffuentesm** [Negodya1/Create-Vintage-Improvements#3]
For some reason, there are two Curving press tabs. The second one only has the Bucket recipe, while the first one has all recipes, including the bucket.  
![image](https://github.com/Negodya1/Create-Vintage-Improvements/assets/44974827/f5d5fcf1-f982-42d1-a18c-42518c75266f)
![image](https://github.com/Negodya1/Create-Vintage-Improvements/assets/44974827/c5ced047-2236-4fdd-9608-03598e5b5ec4)

Also, the recipe for the Dragon Armor does not show the metal blocks for the recipe. 
![image](https://github.com/Negodya1/Create-Vintage-Improvements/assets/44974827/7ff144c3-38f0-4b65-8a1c-29e0a683e0a4)
![image](https://github.com/Negodya1/Create-Vintage-Improvements/assets/44974827/988c590b-d305-49bb-aad4-d64a8b9fabc9)

**Comment by Negodya1** [comment]
Two tabs is not a bag, firts tab for custom recipes, second tab for recipes which recognized automatically (this can be disabled in the config)

Which mod is Dragon Armor from? I will check and fix it in the next update

**Comment by Negodya1** [comment]
Fixed
