### ISSUE TITLE
Some createaddition:rolling recipes have the wrong format.

### ISSUE THREAD

**Issue by omgimanerd** [Negodya1/Create-Vintage-Improvements#31]
`createaddition:rolling` recipe types take an `input:object` key and a `result:object` key. Some of the compat rolling recipes in the pack resources have `ingredients:object[]` and `results:object[]` which is not supported by Create Crafts and Additions.

Example: https://github.com/Negodya1/Create-Vintage-Improvements/blob/1.20.1/src/main/resources/data/vintageimprovements/recipes/rolling/aluminum_ingot.json

**Comment by omgimanerd** [comment]
For reference, here's the recipe serializer for the rolling recipes.
https://github.com/mrh0/createaddition/blob/1.20.1/src/main/java/com/mrh0/createaddition/recipe/rolling/RollingRecipeSerializer.java#L35-L40

**Comment by Negodya1** [comment]
Fixed
