### ISSUE TITLE
Some recipes are missing the conditions entry

### ISSUE THREAD

**Issue by VoidLeech** [Negodya1/Create-Vintage-Improvements#33]
The rolling recipes for the vanadium [ingot](https://github.com/Negodya1/Create-Vintage-Improvements/blob/1.20.1/src/main/resources/data/vintageimprovements/recipes/rolling/vanadium_ingot.json) and [plate](https://github.com/Negodya1/Create-Vintage-Improvements/blob/1.20.1/src/main/resources/data/vintageimprovements/recipes/rolling/vanadium_plate.json) are missing the conditions entry that checks whether createadditions is actually installed, resulting in parsing errors and log clutter if createadditions is not installed.

**Comment by VoidLeech** [comment]
The second recipe in the [tuff recycling](https://github.com/Negodya1/Create-Vintage-Improvements/blob/1.20.1/src/main/resources/data/create/recipes/crushing/tuff_recycling.json) recipe is also missing a conditions entry (as it's part of a forge:conditional block)
This second recipe also doesn't produce the electrum the first recipe does. Either this should be added (and thus add a condition checking for createaddition being loaded), or it should have the condition of {"type": "forge:true"}

**Comment by Negodya1** [comment]
Fixed
