### ISSUE TITLE
KubeJs Support

### ISSUE THREAD

**Issue by Elnhomantia** [Negodya1/Create-Vintage-Improvements#37]
Heelo, I think it would be a lot more practical to create recipes if your mod had a kubejs support. (I don't know if it's hard to make, i'm just making a suggestion)

**Comment by omgimanerd** [comment]
It does not need kubejs support. You can define the recipe schemas for it yourself.

Here is an example: https://github.com/omgimanerd/create-advanced-industries/blob/9548ac3bce3654aba4a9d89c05e204abe0366d65/minecraft/kubejs/startup_scripts/recipeSchemas.js#L117

**Comment by Negodya1** [comment]
KubeJS addon is released

[CurseForge](https://www.curseforge.com/minecraft/mc-mods/vintage-kubejs)
[Modrinth](https://modrinth.com/mod/vintage-kubejs)
