### ISSUE TITLE
Can custom recipes specify ingredients with NBT tags?

### ISSUE THREAD

**Issue by k-kuroguro** [Negodya1/Create-Vintage-Improvements#38]
Hi, Is it possible to specify ingredients with NBT tags in custom recipes? I couldn't find any clear information on this.

**Comment by Negodya1** [comment]
You can use forge:nbt ingredients ([Example](https://github.com/Negodya1/Create-Vintage-Improvements/blob/1.20.1/src/main/resources/data/vintageimprovements/recipes/stonecutting/v_shaped_curving_head.json)), but this has not been tested

**Comment by Negodya1** [comment]
I'v tested, it works, centrifugation example:
[test.json](https://github.com/user-attachments/files/16201836/test.json)

**Comment by k-kuroguro** [comment]
Thx!
