### ISSUE TITLE
Recipe Sequence working weird

### ISSUE THREAD

**Issue by Danymaddox** [Negodya1/Create-Vintage-Improvements#39]
Using Centrifuges in a recipe sequence makes the centrifuge require the 'incpmplete' item FIRST and then any other items. If you try to add first the secondary items and then the 'incomplete' item, the centrifugue does not recognize the recipe.

**Comment by Negodya1** [comment]
Can you send me your recipe? And tell your minecraft version

**Comment by Negodya1** [comment]
Fixed
