### ISSUE TITLE
Curving recipes doesn't show on server in jei

### ISSUE THREAD

**Issue by Proxwian** [Negodya1/Create-Vintage-Improvements#4]
I was trying to add them manually, to data folder, but it seems mod doesn't even try to load them on server. Singleplayer recipes work well

**Comment by Negodya1** [comment]
Works only recipes for grinder, I found a reason and fix it in the next update of the mod. But for now you can fix it yorself, just copy config file from client to server config folder

**Comment by Negodya1** [comment]
Fixed
