### ISSUE TITLE
Not Working on server(1.20.1-0.2.0.1)

### ISSUE THREAD

**Issue by DACDS** [Negodya1/Create-Vintage-Improvements#43]
09.08 22:18:13 [Server] INFO A detailed walkthrough of the error, its code path and all known details is as follows:
09.08 22:18:13 [Server] INFO ---------------------------------------------------------------------------------------
09.08 22:18:13 [Server] INFO -- Head --
09.08 22:18:13 [Server] INFO Thread: main
09.08 22:18:13 [Server] INFO Suspected Mods: NONE
09.08 22:18:13 [Server] INFO Stacktrace:
09.08 22:18:13 [Server] INFO 	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?] {re:mixin}
09.08 22:18:13 [Server] INFO -- MOD vintageimprovements --
09.08 22:18:13 [Server] INFO Details:
09.08 22:18:13 [Server] INFO 	Mod File: /mods/vintageimprovements-1.20.1-0.2.0.1.jar
09.08 22:18:13 [Server] INFO 	Failure message: Create: Vintage Improvements (vintageimprovements) has failed to load correctly
09.08 22:18:13 [Server] INFO 		java.util.ConcurrentModificationException: null
09.08 22:18:13 [Server] INFO 	Mod Version: 1.20.1-0.2.0.1
09.08 22:18:13 [Server] INFO 	Mod Issue URL: NOT PROVIDED
09.08 22:18:13 [Server] INFO 	Exception message: java.util.ConcurrentModificationException
09.08 22:18:13 [Server] INFO Stacktrace:
09.08 22:18:13 [Server] INFO 	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?] {re:mixin}
09.08 22:18:13 [Server] INFO 	at com.negodya1.vintageimprovements.infrastructure.config.VCStress.registerAll(VCStress.java:28) ~[vintageimprovements-1.20.1-0.2.0.1.jar%23503!/:1.20.1-0.2.0.1] {re:classloading}
09.08 22:18:13 [Server] INFO 	at com.simibubi.create.foundation.config.ConfigBase.lambda$nested$0(ConfigBase.java:83) ~[create-1.20.1-0.5.1.f.jar%23351!/:0.5.1.f] {re:classloading}
09.08 22:18:13 [Server] INFO 	at com.simibubi.create.foundation.config.ConfigBase$CValue.lambda$new$0(ConfigBase.java:103) ~[create-1.20.1-0.5.1.f.jar%23351!/:0.5.1.f] {re:mixin,re:classloading}
09.08 22:18:13 [Server] INFO 	at com.simibubi.create.foundation.config.ConfigBase$CValue.register(ConfigBase.java:121) ~[create-1.20.1-0.5.1.f.jar%23351!/:0.5.1.f] {re:mixin,re:classloading}
09.08 22:18:13 [Server] INFO 	at com.simibubi.create.foundation.config.ConfigBase.registerAll(ConfigBase.java:26) ~[create-1.20.1-0.5.1.f.jar%23351!/:0.5.1.f] {re:classloading}
09.08 22:18:13 [Server] INFO 	at com.simibubi.create.foundation.config.ConfigBase.lambda$nested$0(ConfigBase.java:83) ~[create-1.20.1-0.5.1.f.jar%23351!/:0.5.1.f] {re:classloading}
09.08 22:18:13 [Server] INFO 	at com.simibubi.create.foundation.config.ConfigBase$CValue.lambda$new$0(ConfigBase.java:103) ~[create-1.20.1-0.5.1.f.jar%23351!/:0.5.1.f] {re:mixin,re:classloading}
09.08 22:18:13 [Server] INFO 	at com.simibubi.create.foundation.config.ConfigBase$CValue.register(ConfigBase.java:121) ~[create-1.20.1-0.5.1.f.jar%23351!/:0.5.1.f] {re:mixin,re:classloading}
09.08 22:18:13 [Server] INFO 	at com.simibubi.create.foundation.config.ConfigBase.registerAll(ConfigBase.java:26) ~[create-1.20.1-0.5.1.f.jar%23351!/:0.5.1.f] {re:classloading}
09.08 22:18:13 [Server] INFO 	at com.negodya1.vintageimprovements.infrastructure.config.VintageConfig.lambda$register$0(VintageConfig.java:44) ~[vintageimprovements-1.20.1-0.2.0.1.jar%23503!/:1.20.1-0.2.0.1] {re:classloading}
09.08 22:18:13 [Server] INFO 	at net.minecraftforge.common.ForgeConfigSpec$Builder.configure(ForgeConfigSpec.java:609) ~[forge-1.20.1-47.2.17-universal.jar%23522!/:?] {re:classloading}
09.08 22:18:13 [Server] INFO 	at com.negodya1.vintageimprovements.infrastructure.config.VintageConfig.register(VintageConfig.java:42) ~[vintageimprovements-1.20.1-0.2.0.1.jar%23503!/:1.20.1-0.2.0.1] {re:classloading}
09.08 22:18:13 [Server] INFO 	at com.negodya1.vintageimprovements.infrastructure.config.VintageConfig.register(VintageConfig.java:57) ~[vintageimprovements-1.20.1-0.2.0.1.jar%23503!/:1.20.1-0.2.0.1] {re:classloading}
09.08 22:18:13 [Server] INFO 	at com.negodya1.vintageimprovements.VintageImprovements.onCtor(VintageImprovements.java:633) ~[vintageimprovements-1.20.1-0.2.0.1.jar%23503!/:1.20.1-0.2.0.1] {re:classloading}
09.08 22:18:13 [Server] INFO 	at com.negodya1.vintageimprovements.VintageImprovements.<init>(VintageImprovements.java:599) ~[vintageimprovements-1.20.1-0.2.0.1.jar%23503!/:1.20.1-0.2.0.1] {re:classloading}
09.08 22:18:13 [Server] INFO 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
09.08 22:18:13 [Server] INFO 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
09.08 22:18:13 [Server] INFO 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
09.08 22:18:13 [Server] INFO 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
09.08 22:18:13 [Server] INFO 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
09.08 22:18:13 [Server] INFO 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.17.jar%23519!/:?] {}

**Comment by Negodya1** [comment]
Probably fixed =/

**Comment by DACDS** [comment]
Its the new version

**Comment by Negodya1** [comment]
In 0.2.0.2 version

**Comment by DACDS** [comment]
ah
