### ISSUE TITLE
crash when using the helve hammer with smithing

### ISSUE THREAD

**Issue by hooded-person** [Negodya1/Create-Vintage-Improvements#44]
I play on a server which adds smithing recipes for most create items, these require a "crafting blueprint", a machine (say "andesite machine") and say a "brass hand" for a deployer. but when i add 2 of the 3 items to the helve hammer i crash, which is seemingly because it is trying to find a recipe but finds none and then tries to index it as a list.
**crash report:** https://mclo.gs/lOsy0R0
**mod version:** 1.20.1-0.1.6.0
-# **discord bug report**: https://discord.com/channels/1217876699950223461/1277051700342947872/1277051700342947872

**Comment by Negodya1** [comment]
Fixed

**Comment by hooded-person** [comment]
too what version should we update the mod?
